# Generated by Django 4.1.7 on 2023-03-08 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrow_statuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Id_types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item_categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item_statuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='u_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_department', to='Main.department'),
        ),
        migrations.AlterField(
            model_name='user',
            name='u_faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_faculty', to='Main.faculty'),
        ),
        migrations.AlterField(
            model_name='user',
            name='u_privilege',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_privilege', to='Main.user_privileges'),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=200)),
                ('item_name', models.CharField(max_length=200)),
                ('item_description', models.CharField(max_length=200)),
                ('item_note', models.CharField(max_length=200)),
                ('item_img_url', models.CharField(max_length=200)),
                ('item_create_at', models.DateTimeField(auto_now_add=True)),
                ('item_update_at', models.DateTimeField(auto_now=True)),
                ('item_borrow_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_borrow_status', to='Main.borrow_statuses')),
                ('item_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_item_categories', to='Main.item_categories')),
                ('item_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_department', to='Main.department')),
                ('item_faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_faculty', to='Main.faculty')),
                ('item_id_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_id_type', to='Main.id_types')),
                ('item_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_status', to='Main.item_statuses')),
            ],
        ),
        migrations.CreateModel(
            name='Borrow_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_location', models.CharField(max_length=200)),
                ('b_note', models.CharField(max_length=200)),
                ('b_borrow_time', models.DateTimeField(auto_now=True)),
                ('b_return_time', models.DateTimeField(auto_now=True)),
                ('b_create_at', models.DateTimeField(auto_now_add=True)),
                ('b_update_at', models.DateTimeField(auto_now=True)),
                ('b_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_info_item', to='Main.item')),
                ('b_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_info_user', to='Main.user')),
            ],
        ),
    ]
